service: ninebot

provider:
  name: aws
  region: ap-northeast-2
  runtime: nodejs20.x
  memorySize: 512
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
        - 'lambda:InvokeAsync'
      Resource: ${self:custom.message_function_arn}

custom:
  message_function_name: ${self:service}-${opt:stage, 'dev'}-message
  message_function_arn: 'arn:aws:lambda:${aws:region}:${aws:accountId}:function:${self:custom.message_function_name}'

functions:
  slash:
    handler: index.slash
    timeout: 10
    environment:
      MESSAGE_FUNCTION_NAME: ${self:custom.message_function_name}
    events:
      - httpApi:
          path: /slash
          method: post
  message:
    handler: index.message
    timeout: 60
    environment:
      OPENAI_API_KEY: ${file(./env.yml):openaiApiKey}
